<a href="https://colab.research.google.com/github/futurelabmx/cdecmx/blob/main/B%20-%20Intro%20a%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy

A lo largo de este cuaderno explicaremos algunos elementos básicos y herramientas con las que cuenta NumPy. Los temas específicos que cubriremos en este cuaderno introductorio son los siguientes:

1. Introducción a NumPy
2. Atributos, tamaño y forma
3. Creación de arreglos
4. Indexación y slicing
5. Operaciones básicas, broadcasting
6. Valores únicos y cuentas
7. Matrices en NumPy
8. Trasposición, aplanamiento y reversa
9. Reshape de matrices
10. Módulo random
11. Módulo de álgebra lineal
12. Conoce SciPy

### Planteamiento del problema:

El poder manipular datos multidimensionales es generalmente de mucha ayuda, así que utilizaremos algunos de los conceptos previamente mencionados para trabajar con imágenes y descomponerlas en sus diferentes dimensiones (o canales) de color.

## ¿Qué es NumPy?

<center>
    <img width="30%" src="https://numpy.org/images/logos/numpy.svg">
</center>

**NumPy** es el paquete fundamental para la computación numérica con Python.

De acuerdo con Wikipedia: _"(...) es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas."_


### Objetos en NumPy

En NumPy, los objetos con los que trabajamos son arreglos multidimensionales:

```
                     [1, 2, 3, 4] → [1.0 2.0 3.0 4.0]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]] →  [[1.0 2.0 3.0]
                                      [4.0 5.0 6.0]
                                      [7.0 8.0 9.0]]
```

### ¿Qué es un _array_?

Un arreglo es la formalización de una lista en Python; y un array puede ser indexado por una tupla de enteros no negativos, por booleanos, por otro arreglo o por enteros. El rango de la matriz es el número de dimensiones. La forma de la matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Una forma en que podemos inicializar matrices NumPy es a partir de listas de Python, utilizando listas anidadas para datos bidimensionales o de mayor dimensión.




In [ ]:
import numpy as np # ¡IMPORTANTE!


a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a))
print(a[0])
print()

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)
print(type(b))
print(b[0])
print(type(b[0]))

## Atributos, tamaño y forma

Un arreglo suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. El número de **dimensiones** y **elementos** se define por su forma. La **forma (shape)** es una tupla de números enteros no negativos que especifican los tamaños de cada dimensión.

En NumPy, las dimensiones se denominan **ejes (axes)**.

Esto significa que si tenemos un arreglo 2D (una matriz) que se ve así:

```python
[[0., 0., 0.],
 [1., 1., 1.]]
```

Entonces tenemos 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3. (`shape=(2, 3)`)

### ¿Cómo saber la forma y tamaño?

- **ndarray.ndim** te dirá el número de ejes o dimensiones de la matriz.
- **ndarray.size** te dirá el número total de elementos de la matriz. Este es el producto de los elementos de la forma de la matriz.
- **ndarray.shape** te mostrará una tupla de números que indican el número de elementos almacenados a lo largo de cada dimensión de la matriz.





In [ ]:
print(b)
print(b.ndim)
print(b.size)
print(b.shape)

## Creación de arreglos

Además de crear un array a partir de una secuencia de elementos, puedes crear uno llena de ceros, o llena de unos:

```python
np.zeros(2)
# array([0., 0.])
np.ones(2)
# array([1., 1.])
```

#### Ejercicio:

- Crea una matriz de ceros de 5x5 e imprímela en pantalla.
- ¿Puedes crear una matriz identidad? Una matriz identidad es una matriz cuadrada llena de ceros y con unos en la diagonal. Puedes construirla utilizando un ciclo `for` y haciendo uso de los que conocemos hasta ahora para iterar listas en Python.
- Si quieres construir una matriz identidad, también puedes utilizar la función `np.eye()`.

In [ ]:
# TODO.


También puedes usar np.linspace() para crear una matriz con valores espaciados linealmente en un intervalo especificado.

Para esto nos apoyaremos de una biblioteca que nos permite graficar.

In [ ]:
x = np.linspace(0, 50, 51)
print(x)

y = np.sin(x)
print(y)

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('seaborn')


fig = plt.figure(figsize=(20, 5))
plt.plot(x, y)
plt.show()

## Indexación y slicing

Podemos indexar y usar slicing matrices NumPy de la misma manera que hacemos con listas de Python.

```python
data = np.array([1, 2, 3])

print(data[1])
# 2
print(data[0:2])
# array([1, 2])
print(data[1:])
# array([2, 3])
print(data[-2:])
# array([2, 3])
```

La principal diferencia es que en lugar de usar múltiples corchetes, usamos comas para acceder a elementos. Exploremos en un ejemplo:


In [ ]:
print(b)
print(b[0])

## Operaciones básicas, broadcasting

Si tuviésemos un par de arrays del misma forma, podríamos operar entre ellos. Consideremos el par de arreglos a continuación:

<center>
    <img src="https://numpy.org/devdocs/_images/np_array_dataones.png">
</center>

Podríamos sumarlos:

<center>
    <img src="https://numpy.org/devdocs/_images/np_data_plus_ones.png">
</center>

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)


Esto en general se preserva para las otras operaciones básicas:

<center>
    <img src="https://numpy.org/devdocs/_images/np_sub_mult_divide.png">
</center>



In [ ]:
print(data - ones)
print(data * data)
print(data / data)

#### ¿Qué sucede si queremos una multiplicación escalar?

## Broadcasting

<center>
    <img src="https://numpy.org/devdocs/_images/np_multiply_broadcasting.png">
</center>

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

## Valores únicos y cuentas

Existen algunas funciones propias de los arreglos en NumPy:
- **.max()** te dirá el máximo de los elementos del arreglo.
- **.min()** te dirá el mínimo de los elementos del arreglo.
- **.sum()** te dirá la suma  de los elementos del arreglo.
- **.prod()** te dirá el producto de los elementos del arreglo.



In [ ]:
A = np.array([
    [45, 21,  9, 92],
    [76,  2, 12, 35],
    [23, 47, 89, 25],
    [40, 78, 23,  1]
])

Incluso existen funciones que te devuelven estadísticos de tus datos:
- **.mean()** te dirá el promedio de los elementos del arreglo.
- **.std()** te dirá la desviación estándar de los elementos del arreglo.


In [ ]:
B = np.array([45, 21, 9, 92, 76, 2, 12, 35, 23, 47, 89, 25, 40, 78, 23, 1])

En cuanto a querer devolver valores únicos, podemos usar **.uniques()**

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
unique_values = np.unique(a)
print(unique_values)

Finalmente, no hay que olvidar que podemos utilizar operaciones matemáticas básicas:
- **np.sin(x)** te devolverá el seno del vector `x`.
- **np.cos(x)** te devolverá el coseno del vector `x`
- Etcétera.

In [ ]:
np.cos(B)

## Trasposición, aplanamiento y reversa

Es común tener que trasponer matrices. Las matrices NumPy tienen la propiedad **.T** que permite transponer una matriz. De igual manera se puede utilizar **.transpose()**

<center>
    <img src="https://numpy.org/devdocs/_images/np_transposing_reshaping.png">
</center>


In [ ]:
print(A)

En algunas ocasiones resulta útil aplanar una matriz, esto es, convertirla en un arreglo unidimensional. Esto puede lograrse con **.flatten()**


In [ ]:
print(A)

Al igual que con las listas en Python, podemos utilizar slicing para revertir un array, sin embargo, NumPy tiene una función propia: **np.flip()**

#### ¿Qué sucede si lo utilizamos en matrices?


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

In [ ]:
print(A)

### Reshape de matrices

**.reshape()** permite cambiar la forma de una matriz sin cambiar los datos. Sólo ten presente que cuando usamos esta función, la matriz que queremos producir debe tener la misma cantidad de elementos que la matriz original.


In [ ]:
print(A)

## Matrices en NumPy

Procederemos a explorar un poco con una imagen y sus canales de color.


In [ ]:
import urllib.request


image_url = 'https://raw.githubusercontent.com/futurelabmx/cdecmx/gh-pages/assets/images/cdec_python.jpeg'
filename = 'image.jgp'
urllib.request.urlretrieve(image_url, filename)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


In [ ]:
# Sección de código libre

## Módulo random

Conoce más del módulo `random` aquí: https://numpy.org/doc/stable/reference/random/

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

## Módulo de álgebra lineal

Conoce más del módulo `linalg` aquí: https://numpy.org/doc/stable/reference/routines.linalg

## Conoce SciPy

Explora SciPy aquí: https://www.scipy.org/

--------

> Contenido creado por **Rodolfo Ferro** ([CdeCMx](https://clubesdeciencia.mx/) / [Future Lab](https://futurelab.mx/), 2021). <br>
> Contacto: [@rodo_ferro](https://www.instagram.com/rodo_ferro/) & [@FerroRodolfo](https://twitter.com/FerroRodolfo)